add_library(chronolog_kvs store.cpp)
add_library(chronolog::kvs ALIAS chronolog_kvs)
target_include_directories(chronolog_kvs PUBLIC include)
target_link_libraries(chronolog_kvs PUBLIC chronolog::client PRIVATE chronolog_warnings)
add_executable(chronolog_kvs_cli cli.cpp)
set_target_properties(chronolog_kvs_cli PROPERTIES OUTPUT_NAME chronolog_kvs)
target_link_libraries(chronolog_kvs_cli PRIVATE chronolog::kvs chronolog_warnings)
add_executable(chronolog_kvs_example example.cpp)
target_link_libraries(chronolog_kvs_example PRIVATE chronolog::kvs chronolog_warnings)
add_executable(chronolog_kvs_tests tests/store_test.cpp)
target_link_libraries(chronolog_kvs_tests PRIVATE chronolog::kvs chronolog_warnings GTest::gtest)
if(TARGET chrono_visor AND TARGET chrono_keeper AND TARGET chrono_player)
    add_test(NAME kvs.acceptance COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} bash "${PROJECT_SOURCE_DIR}/client/cpp/tests/acceptance.sh"
        $<TARGET_FILE:chrono_visor> $<TARGET_FILE:chrono_keeper> $<TARGET_FILE:chrono_player> $<TARGET_FILE:chronolog_kvs_tests>)
    set_tests_properties(kvs.acceptance PROPERTIES TIMEOUT 90)
endif()
