add_library(chronolog_pubsub bus.cpp)
add_library(chronolog::pubsub ALIAS chronolog_pubsub)
target_include_directories(chronolog_pubsub PUBLIC include)
target_link_libraries(chronolog_pubsub PUBLIC chronolog::client chronolog::kvs PRIVATE chronolog_warnings Threads::Threads)
add_executable(chronolog_pubsub_example example.cpp)
target_link_libraries(chronolog_pubsub_example PRIVATE chronolog::pubsub chronolog_warnings)
add_executable(chronolog_pubsub_tests tests/bus_test.cpp)
target_link_libraries(chronolog_pubsub_tests PRIVATE chronolog::pubsub GTest::gtest chronolog_warnings Threads::Threads)
if(TARGET chrono_visor AND TARGET chrono_keeper AND TARGET chrono_player)
    add_test(NAME pubsub.acceptance COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} bash "${CMAKE_CURRENT_SOURCE_DIR}/tests/acceptance.sh"
        $<TARGET_FILE:chrono_visor> $<TARGET_FILE:chrono_keeper> $<TARGET_FILE:chrono_player> $<TARGET_FILE:chronolog_pubsub_tests>)
    set_tests_properties(pubsub.acceptance PROPERTIES TIMEOUT 90)
endif()
