apiVersion: 1
datasources:
  - name: ChronoLog telemetry
    uid: chronolog-stream-influx
    type: influxdb
    access: proxy
    isDefault: true
    url: http://127.0.0.1:8086
    jsonData:
      version: Flux
      organization: chronolog
      defaultBucket: telemetry
      httpMode: POST
    secureJsonData:
      token: ${INFLUX_TOKEN}
