set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)
string(APPEND VCPKG_C_FLAGS " -fsanitize=address,undefined -fno-omit-frame-pointer")
string(APPEND VCPKG_CXX_FLAGS " -fsanitize=address,undefined -fno-omit-frame-pointer")
