[build-system]
requires = ["scikit-build-core>=1.1", "nanobind>=3.1"]
build-backend = "scikit_build_core.build"

[project]
name = "chronolog"
version = "4.0.0"
requires-python = ">=3.12"

[project.optional-dependencies]
otel = ["opentelemetry-sdk>=1.39,<2"]

[tool.scikit-build]
cmake.source-dir = "../.."
cmake.args = ["--preset=python"]
cmake.build-type = "Debug"
build.targets = ["_core"]
install.components = ["python"]
wheel.packages = ["chronolog"]
wheel.py-api = "cp312"
build-dir = "../../build/python"
