FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git g++ python3 curl build-essential unzip tar \
    libtool autoconf automake pkg-config jq lsof cmake chrpath

# Create grc-iit user to match local.dockerfile
ARG USERNAME=grc-iit
ARG UID=1001
RUN id $UID && userdel $(id -un $UID) || : \
 && useradd -m -u $UID -s /bin/bash $USERNAME \
 && echo "$USERNAME ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME \
 && passwd -d $USERNAME

# Clone Spack
RUN git clone --branch v0.21.2 https://github.com/spack/spack.git /opt/spack && \
    echo "source /opt/spack/share/spack/setup-env.sh" >> /etc/bash.bashrc

# Setup Spack in PATH
ENV SPACK_ROOT=/opt/spack
ENV PATH=$SPACK_ROOT/bin:$PATH
SHELL ["/bin/bash", "-c"]

WORKDIR /workspace
