add_library(chronolog_sql database.cpp parser.cpp)
add_library(chronolog::sql ALIAS chronolog_sql)
target_include_directories(chronolog_sql PUBLIC include)
target_link_libraries(chronolog_sql PUBLIC chronolog::client nlohmann_json::nlohmann_json PRIVATE chronolog_warnings)
add_executable(chronolog_sql_cli cli.cpp)
set_target_properties(chronolog_sql_cli PROPERTIES OUTPUT_NAME chronolog_sql)
target_link_libraries(chronolog_sql_cli PRIVATE chronolog::sql chronolog_warnings)
add_executable(chronolog_sql_example example.cpp)
target_link_libraries(chronolog_sql_example PRIVATE chronolog::sql chronolog_warnings)
add_executable(chronolog_sql_tests tests/parser_test.cpp)
target_link_libraries(chronolog_sql_tests PRIVATE chronolog::sql GTest::gtest_main chronolog_warnings)
include(GoogleTest)
gtest_discover_tests(chronolog_sql_tests TEST_PREFIX "sql." DISCOVERY_MODE PRE_TEST PROPERTIES TIMEOUT 20)
add_executable(chronolog_sql_acceptance tests/acceptance.cpp)
target_link_libraries(chronolog_sql_acceptance PRIVATE chronolog::sql GTest::gtest Threads::Threads chronolog_warnings)
if(TARGET chrono_visor AND TARGET chrono_keeper AND TARGET chrono_player)
    add_test(NAME sql.acceptance COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} bash "${CMAKE_CURRENT_SOURCE_DIR}/tests/acceptance.sh"
        $<TARGET_FILE:chrono_visor> $<TARGET_FILE:chrono_keeper> $<TARGET_FILE:chrono_player> $<TARGET_FILE:chronolog_sql_acceptance>)
    set_tests_properties(sql.acceptance PROPERTIES TIMEOUT 90)
endif()
