# ctest body for build.no_legacy_transport (M11.4). Usage: cmake -DROOT=<source dir> -P NoLegacyTransportCheck.cmake
# Walks every CMakeLists.txt the build reads, starting at the root and following literal add_subdirectory calls,
# and checks them and vcpkg.json for Argobots, Thallium, Margo, Mochi and RDMA packages.
if(NOT ROOT)
    message(FATAL_ERROR "ROOT is required")
endif()
set(pattern "argobots|thallium|margo|mochi|mercury|rdma|libfabric|ibverbs|ucx|ofi\\+verbs")
set(pending "${ROOT}")
set(scanned "")
set(violations "")
while(pending)
    list(POP_FRONT pending dir)
    set(file "${dir}/CMakeLists.txt")
    if(NOT EXISTS "${file}" OR "${file}" IN_LIST scanned)
        continue()
    endif()
    list(APPEND scanned "${file}")
    file(READ "${file}" text)
    string(TOLOWER "${text}" lowered)
    if(lowered MATCHES "${pattern}")
        list(APPEND violations "${file}: ${CMAKE_MATCH_0}")
    endif()
    string(REGEX MATCHALL "add_subdirectory\\([^)]*\\)" calls "${text}")
    foreach(call IN LISTS calls)
        string(REGEX REPLACE "add_subdirectory\\([ \t\r\n]*([^ \t\r\n)]+).*" "\\1" sub "${call}")
        string(REPLACE "\"" "" sub "${sub}")
        if(sub MATCHES "\\$")
            continue()
        endif()
        list(APPEND pending "${dir}/${sub}")
    endforeach()
endwhile()
if(EXISTS "${ROOT}/vcpkg.json")
    file(READ "${ROOT}/vcpkg.json" manifest)
    string(TOLOWER "${manifest}" manifest)
    if(manifest MATCHES "${pattern}")
        list(APPEND violations "${ROOT}/vcpkg.json: ${CMAKE_MATCH_0}")
    endif()
endif()
list(LENGTH scanned count)
if(count LESS 10)
    message(FATAL_ERROR "scanned only ${count} CMakeLists.txt files; the add_subdirectory walk is broken")
endif()
if(violations)
    string(REPLACE ";" "\n  " report "${violations}")
    message(FATAL_ERROR "legacy transport found:\n  ${report}")
endif()
message(STATUS "no legacy transport in ${count} CMakeLists.txt files and vcpkg.json")
